export const getInitialState = (portalUrl: string, userBGVData: any) => {
  return {
    Company_Portal_Url: portalUrl,
    PersonalDetails: {
      First_Name: userBGVData?.FirstName || "",
      Last_Name: userBGVData?.LastName || "",
      Middle_Name: userBGVData?.MiddleName || "",
      Father_Name: userBGVData?.FatherName || "",
      Mobile_Number: userBGVData?.MobileNumber || "",
      Marital_Status: userBGVData?.Marital_Status || "",
      Date_of_Birth: userBGVData?.Date_of_Birth || "",
      Passport_Size_Photo: "",
    },
    IdentityDetails: {
      Passport_Number: "",
      Re_enter_Passport_Number: "",
      Passport_Image: "",
      Passport_FieldNumber: "",
      UAN_Number: "",
      Re_enter_UAN_Number: "",
      PAN_Number: "",
      Re_enter_PAN_Number: "",
      PAN_Image: "",
      Aadhar_Number: "",
      Re_enter_Aadhar_Number: "",
      Aadhar_Image: "",
    },
    ResidentialDetails: {
      CurrentAddress_Street: userBGVData?.CurrentAddress_Street || "",
      CurrentAddress_City: userBGVData?.CurrentAddress_City || "",
      CurrentAddress_State: userBGVData?.CurrentAddress_State || "",
      CurrentAddress_PINcode: userBGVData?.CurrentAddress_PINcode || "",
      CurrentAddress_Country: userBGVData?.CurrentAddress_Country || "",
      PermanentAddress_Street: userBGVData?.PermanentAddress_Street || "",
      PermanentAddress_City: userBGVData?.PermanentAddress_City || "",
      PermanentAddress_State: userBGVData?.PermanentAddress_State || "",
      PermanentAddress_PINcode: userBGVData?.PermanentAddress_PINcode || "",
      PermanentAddress_Country: userBGVData?.PermanentAddress_Country || "",
    },
    EducationalDetails: [
      {
        EducationType: "",
        Degree: "",
        Department: "",
        Education_Certificate_Image: "",
        EndDate: "",
        InstitutionName: "",
        StartDate: "",
        Transcriptions_Image: "",
      },
    ],
    EmploymentDetails: [
      {
        CompanyName: "",
        EndDate: "",
        JobTitle: "",
        OfferLetterImage: "",
        RelievingletterImage: "",
        StartDate: "",
        CurrentlyWorking: false,
      },
    ],
  };
};
